### ISSUE TITLE
Pictures

### ISSUE THREAD

**Issue by knight42** [knight42/homebrew-tap#2]

**Comment by knight42** [comment]
![audit](https://user-images.githubusercontent.com/4237254/226959542-57193653-0afe-4a8b-bee6-ab96bacdfa83.gif)

**Comment by knight42** [comment]
![diagnose](https://user-images.githubusercontent.com/4237254/226960414-a343b624-b95f-479c-840f-10fb9dc5de05.gif)

**Comment by FogDong** [comment]
![diagnose](https://user-images.githubusercontent.com/15977536/227199412-0a4b4967-a456-4b81-a1e8-47891bf08af2.gif)

**Comment by FogDong** [comment]
![audit](https://user-images.githubusercontent.com/15977536/227199946-04ea075a-787b-4871-aa25-4a8180c84f84.gif)
